version: '3.3'
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - marvin
    env_file: .env
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - marvin
    env_file: .env
    expose:
      - "3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - marvin
    env_file: .env
    expose:
      - "9000"
    restart: always
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jsarabia/data/wordpress
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jsarabia/data/mariadb
networks:
  marvin:
    driver: bridge