version: '3.3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - marvin
    env_file: .env
    expose:
      - "3306"
    restart: always
    volumes:
      - mysql:/var/lib/mysql
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - marvin
    env_file: .env
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - marvin
    env_file: .env
    expose:
      - "9000"
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./requirements/wordpress/config/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jsarabia/data/wordpress
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jsarabia/data/mysql
networks:
  marvin:
    #driver: bridge